### ISSUE TITLE
Drupal 9 version

### ISSUE THREAD

**Issue by MPParsley** [Zeticon/drupal-media-mediahaven#27]
Are there any plans for a Drupal 9 Drupal MediaHaven API v2 plugin?

**Comment by nvercamm** [comment]
For our drupal integration we work together with https://www.calibrate.be/nl. They provide a white label drupal site for MediaHaven. In that regard we are not planning on implementing a new Drupal plugin for Drupal version 9 based on the API v2.

**Comment by MPParsley** [comment]
Thanks for the input @nvercamm.
